### ISSUE TITLE
[FEATURE] Add IsConnected Property

### ISSUE THREAD

**Issue by threeeye** [Johno-ACSLive/ACS-Messaging#2]
**Is your feature request related to a problem? Please describe.**
I modified my code that if the Server crashes or the Client is loaded before the Server, the Client would try to connect to the Server until it has a connection.
Then the Client sends "info" to the Server, but it comes multiple times, I tried putting the thread to sleep, that doesn't help.

**Describe the solution you'd like**
I'd like to have a Client.IsConnected (or something like that) so I'll be able to do:
`If Client.IsConnected Then Client.SendData(MyData)`

**Additional context**
Thanks for all your had work!

**Comment by Johno-ACSLive** [comment]
I'm not sure about duplicate data - this might be related to your send or receive code. I can certainly add this property but you can do this yourself if you subscribe to the event handler for connection accepted, connection failed and connection closed. basically if connection accepted then your variable can be set to true, else if failed or closed it can be false. This will get you going for now. Those handlers are important as you may want to treat a failure vs closed differently etc.

In terms of duplicate data can you provide code examples?

**Comment by threeeye** [comment]
I think this should be changed into a Bug (but I'm not sure, maybe I'm doing something wrong...)
> you can do this yourself if you subscribe to the event handler for connection accepted
That is what I did.

This is my code on the client:
```
    Dim IsConnected As Boolean = False
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ClientInfo = "Computer-Name;192.168.1.121;Windows 10 Enterprise LTSC 2021;MyUserName"
        'In reality I get the above info from a set of functions that are not in this post...
        'If you want to see them, let me know ;)

        Connect()

        If IsConnected Then SendInfo()
    End Sub

    Private Sub Connect()
        Client = New MessageClient("192.168.1.121", 64555, False)

        AddHandler Client.ConnectionAccepted, AddressOf ConnectionAccepted
        AddHandler Client.ConnectionClosed, AddressOf ConnectionClosed
        AddHandler Client.MessageReceived, AddressOf MessageReceived
        AddHandler Client.ConnectionFailed, AddressOf ConnectionFailed

        Client.Connect()
    End Sub
    Private Sub SendInfo()
        Threading.Thread.Sleep(1000)
        Dim data As Byte() = Encoding.ASCII.GetBytes(ClientInfo)
        Client.SendData(data)
    End Sub

    Private Sub ConnectionAccepted(sender As Object, e As ConnectionEventArgs)
        IsConnected = True
    End Sub

    Private Sub ConnectionClosed(sender As Object, e As ConnectionEventArgs)
        IsConnected = False
    End Sub

    Private Sub ConnectionFailed(sender As Object, e As ConnectionEventArgs)
        IsConnected = False

        Do While IsConnected = False
            Connect()
            Threading.Thread.Sleep(1000)
        Loop

        If IsConnected Then SendInfo()
    End Sub
```
![image](https://user-images.githubusercontent.com/404815/165989745-9eea44e2-8c8d-469c-bbb7-757c1172effa.png)
(X is the number of times the server called the AddClient sub (adding the info to the DataGridView), C is the numbet of Clients the server thinks are connected (from Server.Hosts.Count)
On Row 3 on the DGV, the last column got a little info from the next rows first column...

It doesn't matter if I do 
```
        Do While IsConnected = False
            Connect()
            Threading.Thread.Sleep(1000)
        Loop
```
Or
```
        Do Until IsConnected = True
            Connect()
            Threading.Thread.Sleep(1000)
        Loop
```
I always get multiple connections.
The first pic is "Do While IsConnected = False"
This pic is "Do Until IsConnected = True"
![image](https://user-images.githubusercontent.com/404815/165991013-50591338-fc2a-451b-b92f-cd6be7d37c51.png)

**Comment by Johno-ACSLive** [comment]
Row 3 could either be a parsing issue in your code or it could be that you aren't handling framing correctly (it's possible the data is being sent in different packets if you are sending the data multiple times).

The projects I'm using with this library haven't shown these issues. I'll provide some sample code for how you can handle framing until it's added to the library.

I'll check the connection duplication issue, I've not seen it happen but I'll double check that.

**Comment by threeeye** [comment]
OK, I fixed it, it was me being an idiot...

Now I get only 1 entry when I load the client before the server, or "crash" the server and reload it (also if i close the client and reload it)

But a IsConnected property is always helpful...

**Comment by Johno-ACSLive** [comment]
Ok, I'll look at adding that property. I might also look at adding message framing to the samples as well.

**Comment by threeeye** [comment]
Thanks

**Comment by Johno-ACSLive** [comment]
Included in https://github.com/Johno-ACSLive/ACS-Messaging/commit/87cc0bd237b43202dbba08ca8a5f8f080064c9e2
